# 定义工作流程的名字
name: PushPlus

# 规定工作流程何时触发
on:
  # 定时任务触发器，基于cron表达式
  schedule:
    # 北京时间早上8点40分对应的UTC时间为前一天的16点40分 触发此工作流
    - cron: '40 0 * * *'  # Saylove Reminder (调整为UTC时间)
    # 每天北京时间中午11点（UTC时间早上3点）触发此工作流
    - cron: '00 03 * * *'  # Event Reminder
    # 每天北京时间晚上21点（UTC时间13点）触发此工作流
    - cron: '00 13 * * *'  # Weather Reminder
  # 允许手动触发工作流
  workflow_dispatch:

# 定义一个任务
jobs:
  # 使用条件表达式来定义不同类型的提醒任务
  build:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 第二步：设置Python环境
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 第三步：安装Python依赖
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "Error: 未找到 requirements.txt 文件"
            exit 1
          fi

      # 第四步：设置PYTHONPATH环境变量
      - name: Set up PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      # 第五步：根据触发时间选择性地运行相应的脚本
      - name: Run Saylove Reminder Script
        if: github.event_name == 'schedule' && github.event.schedule == '40 0 * * *' || github.event_name == 'workflow_dispatch'
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          TIAN_KEY: ${{ secrets.TIAN_KEY }}
          PUSHPLUS_GROUP_TOPIC: ${{ secrets.PUSHPLUS_GROUP_TOPIC }}
        run: |
          python pushplus/Love_Reminder/Saylove.py

      - name: Run Event Reminder Script
        if: github.event_name == 'schedule' && github.event.schedule == '00 03 * * *' || github.event_name == 'workflow_dispatch'
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          CalendarAPI_KEY: ${{ secrets.CalendarAPI_KEY }}
          PUSHPLUS_GROUP_TOPIC: ${{ secrets.PUSHPLUS_GROUP_TOPIC }}
        run: |
          python pushplus/Event_Reminder/Event.py

      - name: Run Weather Reminder Script
        if: github.event_name == 'schedule' && github.event.schedule == '00 13 * * *' || github.event_name == 'workflow_dispatch'
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          AMAP_KEY: ${{ secrets.AMAP_KEY }}
          PUSHPLUS_GROUP_TOPIC: ${{ secrets.PUSHPLUS_GROUP_TOPIC }}
        run: |
          python pushplus/Weather_Reminder/Weather.py